import Image from "next/image";

export default function Imagens() {
  return (
    <>
      <Image
        className="estrela-do-mar"
        src="/../public/images/estrela-do-mar.png"
        width={70}
        height={70}
      />
      <Image
        className="guarda-sol"
        src="/../public/images/guarda-sol1.png"
        width={170}
        height={170}
      />
      <Image
        className="concha-do-mar"
        src="/../public/images/concha-do-mar.png"
        width={50}
        height={50}
      />
      <Image
        className="folhas-de-coqueiro"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro2"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro3"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro4"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro5"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro6"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro7"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="folhas-de-coqueiro8"
        src="/../public/images/folhas-de-coqueiro5.png"
        width={190}
        height={190}
      />
      <Image
        className="toalha"
        src="/../public/images/toalha1.png"
        width={130}
        height={130}
      />
    </>
  );
}
