import "../src/styles/globals.css";

export const metadata = {
  title: "Portifólio Danillo",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Oswald:wght@400;500&display=swap');
        </style>
      </head>
      <body>{children}</body>
    </html>
  );
}
